name: qr_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pretty_qr_code: ^3.3.0
  share_plus: ^10.1.2
  screenshot: ^3.0.0
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/Manrope-Bold.ttf
  #       - asset: assets/fonts/Manrope-ExtraBold.ttf
  #       - asset: assets/fonts/Manrope-ExtraLight.ttf
  #       - asset: assets/fonts/Manrope-Light.ttf
  #       - asset: assets/fonts/Manrope-Medium.ttf
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #       - asset: assets/fonts/Manrope-SemiBold.ttf
